name: sync
on: push
jobs:
    repo-sync:
        runs-on: ubuntu-latest
        steps:
            - name: repo-sync
              uses: wei/git-sync@v2
              with:
                  source_repo: "https://github.com/qoute/qoute.git"
                  source_branch: "master"
                  destination_repo: "git@git.gitmono.com:qoute.git"
                  destination_branch: "master"
                  ssh_private_key: ${{ secrets.sync_key }}
